# Site settings
title: ZHENGWEI (WILLIAM) MA
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: William Ma
user_description: I'm a senior data scientist.
user_title: Senior Data Scientist
email: williammaucla@gmail.com
# twitter_username: lorem_ipsum
github_username:  wmaucla
# gplus_username:  lorem_ipsum


exclude: ['package.json', 'src' , 'node_modules']
